name: emission_tracker
description: A new Flutter project to track carbon emissions
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1 
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  pin_code_fields: ^8.0.1

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  intl: ^0.20.1

  flutter_map: ^6.1.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.6
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  fl_chart: ^0.69.0
  location: ^6.0.2
  flutter_svg: ^2.2.1
  url_launcher: ^6.1.10
  curved_navigation_bar: ^1.0.6
  animations: ^2.0.11
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/nayla.png
    - assets/awan.svg
    - assets/Vector.svg
    - assets/header.svg
    - assets/komunitas1.png
    - assets/komunitas4.png
    - assets/komunitas5.png
    - assets/komunitas2.png
    - assets/komunitas3.png
    - models/dummy_login.json

